//! Luxor Trend Strategy - Tomasini 2-MA Crossover Implementation
//!
//! This WASM module implements the Tomasini 2-Moving Average Crossover strategy:
//! - Short MA (fast): 10 periods
//! - Long MA (slow): 30 periods
//! - Entry: Fast MA crosses above Slow MA (BUY) or below (SELL)
//! - Risk: MAE stop at 1.5%, MFE profit target at 3%
//! - Time filter: Market hours only (9:30-16:00 EST)

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

// Initialize panic hook for better error messages in WASM
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}

/// Trading action types for strategy signals
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Action {
    /// Enter long position
    Buy,
    /// Exit position or enter short
    Sell,
    /// No action taken
    Hold,
}

/// Market data point for a single timestamp
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketData {
    /// Unix timestamp in milliseconds
    pub timestamp: u64,
    /// Opening price
    pub open: f64,
    /// Highest price in period
    pub high: f64,
    /// Lowest price in period
    pub low: f64,
    /// Closing price
    pub close: f64,
    /// Trading volume
    pub volume: u64,
}

/// Trading signal generated by the strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Unix timestamp in milliseconds when signal was generated
    pub timestamp: u64,
    /// Recommended trading action
    pub action: Action,
    /// Price at signal generation
    pub price: f64,
    /// Confidence score (0.0 to 1.0)
    pub confidence: f64,
}

/// Represents a completed trade
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    /// Entry price of the position
    pub entry_price: f64,
    /// Exit price of the position
    pub exit_price: f64,
    /// Quantity traded
    pub quantity: f64,
    /// Unix timestamp in milliseconds when position was opened
    pub entry_time: u64,
    /// Unix timestamp in milliseconds when position was closed
    pub exit_time: u64,
}

/// Result of a backtest execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestResult {
    /// Sharpe ratio calculated from returns
    pub sharpe_ratio: f64,
    /// Maximum drawdown as percentage (0.0 to 1.0)
    pub max_drawdown: f64,
    /// Total return as percentage (0.0 to 1.0)
    pub total_return: f64,
    /// List of all executed trades
    pub trades: Vec<Trade>,
}

/// Configuration for the Luxor Trend strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    /// Fast moving average period (default: 10)
    pub fast_ma_period: usize,
    /// Slow moving average period (default: 30)
    pub slow_ma_period: usize,
    /// Maximum Adverse Excursion stop loss percentage (default: 0.015 = 1.5%)
    pub mae_stop_pct: f64,
    /// Maximum Favorable Excursion profit target percentage (default: 0.03 = 3%)
    pub mfe_target_pct: f64,
    /// Trading quantity per trade (default: 1.0)
    pub quantity: f64,
}

impl Default for StrategyConfig {
    fn default() -> Self {
        Self {
            fast_ma_period: 10,
            slow_ma_period: 30,
            mae_stop_pct: 0.015,
            mfe_target_pct: 0.03,
            quantity: 1.0,
        }
    }
}

/// Position state tracking for MAE/MFE
#[derive(Debug, Clone)]
struct Position {
    entry_price: f64,
    entry_time: u64,
    quantity: f64,
    direction: i8, // 1 for long, -1 for short
    max_favorable: f64,
    max_adverse: f64,
}

impl Position {
    fn new(entry_price: f64, entry_time: u64, quantity: f64, direction: i8) -> Self {
        Self {
            entry_price,
            entry_time,
            quantity,
            direction,
            max_favorable: entry_price,
            max_adverse: entry_price,
        }
    }

    fn update_mae_mfe(&mut self, price: f64) {
        if self.direction == 1 {
            // Long position
            if price > self.max_favorable {
                self.max_favorable = price;
            }
            if price < self.max_adverse {
                self.max_adverse = price;
            }
        } else {
            // Short position
            if price < self.max_favorable {
                self.max_favorable = price;
            }
            if price > self.max_adverse {
                self.max_adverse = price;
            }
        }
    }

    fn check_stop_loss(&self, current_price: f64, mae_pct: f64) -> bool {
        let loss_pct = if self.direction == 1 {
            (self.entry_price - current_price) / self.entry_price
        } else {
            (current_price - self.entry_price) / self.entry_price
        };
        loss_pct >= mae_pct
    }

    fn check_profit_target(&self, current_price: f64, mfe_pct: f64) -> bool {
        let gain_pct = if self.direction == 1 {
            (current_price - self.entry_price) / self.entry_price
        } else {
            (self.entry_price - current_price) / self.entry_price
        };
        gain_pct >= mfe_pct
    }
}

/// Calculate Simple Moving Average
fn calculate_sma(prices: &[f64], period: usize) -> Option<f64> {
    if prices.len() < period || period == 0 {
        return None;
    }
    let sum: f64 = prices.iter().rev().take(period).sum();
    Some(sum / period as f64)
}

/// Detect if a crossover occurred
/// Returns: Some(1) for bullish crossover, Some(-1) for bearish, None for no crossover
fn detect_crossover(prev_fast: f64, prev_slow: f64, curr_fast: f64, curr_slow: f64) -> Option<i8> {
    let prev_diff = prev_fast - prev_slow;
    let curr_diff = curr_fast - curr_slow;

    // Check for bullish crossover: was below, now above
    if prev_diff <= 0.0 && curr_diff > 0.0 {
        return Some(1);
    }
    // Check for bearish crossover: was above, now below
    if prev_diff >= 0.0 && curr_diff < 0.0 {
        return Some(-1);
    }
    None
}

/// Check if timestamp is within market hours (9:30-16:00 EST)
/// Note: This is a simplified check assuming EST timezone in timestamp
fn is_market_hours(timestamp_ms: u64) -> bool {
    // Convert to seconds for easier manipulation
    let timestamp_sec = timestamp_ms / 1000;

    // Get hour and minute (simplified, assumes timestamp is in EST)
    // In a real implementation, you'd use chrono for proper timezone handling
    let seconds_in_day = timestamp_sec % 86400;
    let hour = (seconds_in_day / 3600) as u32;
    let minute = ((seconds_in_day % 3600) / 60) as u32;

    // Market hours: 9:30 - 16:00
    if hour < 9 || hour >= 16 {
        return false;
    }
    if hour == 9 && minute < 30 {
        return false;
    }
    true
}

/// Main strategy processor
pub struct LuxorTrendStrategy {
    config: StrategyConfig,
    position: Option<Position>,
    trades: Vec<Trade>,
    price_history: Vec<f64>,
}

impl LuxorTrendStrategy {
    pub fn new(config: StrategyConfig) -> Self {
        Self {
            config,
            position: None,
            trades: Vec::new(),
            price_history: Vec::new(),
        }
    }

    /// Process a single market data point
    pub fn process_data(&mut self, data: &MarketData) -> Signal {
        let price = data.close;
        self.price_history.push(price);

        // Check market hours
        let in_market_hours = is_market_hours(data.timestamp);

        // Calculate MAs if we have enough data
        let fast_ma = calculate_sma(&self.price_history, self.config.fast_ma_period);
        let slow_ma = calculate_sma(&self.price_history, self.config.slow_ma_period);

        // Update MAE/MFE for existing position
        if let Some(ref mut pos) = self.position {
            pos.update_mae_mfe(price);
        }

        // Check exit conditions first (risk management)
        let should_exit = if let Some(ref pos) = self.position {
            if !in_market_hours {
                // Exit at market close
                true
            } else if pos.check_stop_loss(price, self.config.mae_stop_pct) {
                // MAE stop hit
                true
            } else if pos.check_profit_target(price, self.config.mfe_target_pct) {
                // MFE target hit
                true
            } else {
                false
            }
        } else {
            false
        };

        if should_exit {
            // Take ownership of position to avoid borrow issues
            if let Some(pos) = self.position.take() {
                let trade = Trade {
                    entry_price: pos.entry_price,
                    exit_price: price,
                    quantity: pos.quantity,
                    entry_time: pos.entry_time,
                    exit_time: data.timestamp,
                };
                self.trades.push(trade);
                return Signal {
                    timestamp: data.timestamp,
                    action: if pos.direction == 1 {
                        Action::Sell
                    } else {
                        Action::Buy
                    },
                    price,
                    confidence: 1.0,
                };
            }
        }

        // Check entry conditions (only during market hours)
        if in_market_hours {
            if let (Some(curr_fast), Some(curr_slow)) = (fast_ma, slow_ma) {
                // Need at least 2 data points for crossover detection
                if self.price_history.len() >= self.config.slow_ma_period + 1 {
                    let prev_prices = &self.price_history[..self.price_history.len() - 1];
                    let prev_fast = calculate_sma(prev_prices, self.config.fast_ma_period);
                    let prev_slow = calculate_sma(prev_prices, self.config.slow_ma_period);

                    if let (Some(p_fast), Some(p_slow)) = (prev_fast, prev_slow) {
                        if let Some(crossover) =
                            detect_crossover(p_fast, p_slow, curr_fast, curr_slow)
                        {
                            // Only enter if not already in a position
                            if self.position.is_none() {
                                let direction = crossover;
                                self.position = Some(Position::new(
                                    price,
                                    data.timestamp,
                                    self.config.quantity,
                                    direction,
                                ));
                                return Signal {
                                    timestamp: data.timestamp,
                                    action: if direction == 1 {
                                        Action::Buy
                                    } else {
                                        Action::Sell
                                    },
                                    price,
                                    confidence: (curr_fast - curr_slow).abs() / curr_slow,
                                };
                            }
                        }
                    }
                }
            }
        }

        Signal {
            timestamp: data.timestamp,
            action: Action::Hold,
            price,
            confidence: 0.0,
        }
    }

    /// Generate signals for all data points
    pub fn generate_signals(&mut self, data: &[MarketData]) -> Vec<Signal> {
        data.iter().map(|d| self.process_data(d)).collect()
    }

    /// Calculate backtest results
    pub fn calculate_backtest(&self, initial_capital: f64) -> BacktestResult {
        let mut returns: Vec<f64> = Vec::new();
        let mut cumulative_return: f64 = 0.0;
        let mut peak_value: f64 = initial_capital;
        let mut current_value: f64 = initial_capital;
        let mut max_drawdown: f64 = 0.0;

        for trade in &self.trades {
            let trade_return = if trade.entry_price > 0.0 {
                ((trade.exit_price - trade.entry_price) / trade.entry_price) * trade.quantity
            } else {
                0.0
            };

            current_value += trade_return * initial_capital;
            let trade_return_pct = trade_return;
            returns.push(trade_return_pct);
            cumulative_return += trade_return_pct;

            if current_value > peak_value {
                peak_value = current_value;
            }

            let drawdown = (peak_value - current_value) / peak_value;
            if drawdown > max_drawdown {
                max_drawdown = drawdown;
            }
        }

        let total_return = (current_value - initial_capital) / initial_capital;
        let sharpe_ratio = calculate_sharpe_ratio(&returns);

        BacktestResult {
            sharpe_ratio,
            max_drawdown,
            total_return,
            trades: self.trades.clone(),
        }
    }
}

/// Calculate Sharpe ratio from returns
fn calculate_sharpe_ratio(returns: &[f64]) -> f64 {
    if returns.is_empty() {
        return 0.0;
    }

    let mean = returns.iter().sum::<f64>() / returns.len() as f64;

    if returns.len() < 2 {
        return if mean > 0.0 { mean } else { 0.0 };
    }

    let variance =
        returns.iter().map(|r| (r - mean).powi(2)).sum::<f64>() / (returns.len() - 1) as f64;

    let std_dev = variance.sqrt();

    if std_dev == 0.0 {
        return if mean > 0.0 { mean } else { 0.0 };
    }

    mean / std_dev
}

/// WASM-exposed function to run backtest
#[wasm_bindgen]
pub fn run_backtest_wasm(data_json: &str) -> String {
    let data: Vec<MarketData> = match serde_json::from_str(data_json) {
        Ok(d) => d,
        Err(e) => return format!("{{\"error\":\"{}\"}}", e),
    };

    let config = StrategyConfig::default();
    let mut strategy = LuxorTrendStrategy::new(config);
    let _signals = strategy.generate_signals(&data);
    let result = strategy.calculate_backtest(10000.0);

    match serde_json::to_string(&result) {
        Ok(json) => json,
        Err(e) => format!("{{\"error\":\"{}\"}}", e),
    }
}

/// WASM-exposed function to generate signals
#[wasm_bindgen]
pub fn generate_signals_wasm(data_json: &str) -> String {
    let data: Vec<MarketData> = match serde_json::from_str(data_json) {
        Ok(d) => d,
        Err(e) => return format!("{{\"error\":\"{}\"}}", e),
    };

    let config = StrategyConfig::default();
    let mut strategy = LuxorTrendStrategy::new(config);
    let signals = strategy.generate_signals(&data);

    match serde_json::to_string(&signals) {
        Ok(json) => json,
        Err(e) => format!("{{\"error\":\"{}\"}}", e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate synthetic AAPL-like data for testing
    fn generate_synthetic_aapl_data(days: usize) -> Vec<MarketData> {
        let mut data = Vec::with_capacity(days);
        let base_price: f64 = 150.0;
        let volatility: f64 = 0.02;
        let trend: f64 = 0.0005;

        // Starting timestamp: Jan 3, 2024 9:30 AM EST in milliseconds
        let mut timestamp: u64 = 1704295800000;

        for i in 0..days {
            // Simulate daily price movement with trend and volatility
            let random_factor: f64 =
                1.0 + (i as f64 * trend) + (volatility * (i as f64).sin() * 0.5);
            let close: f64 = base_price * random_factor * (1.0 + (i as f64 * 0.01).sin() * 0.03);
            let open: f64 = close * (1.0 + (volatility * 0.5 * ((i as f64) * 1.3).sin()));
            let high: f64 = open.max(close) * (1.0 + volatility * 0.3);
            let low: f64 = open.min(close) * (1.0 - volatility * 0.3);

            // Only add trading days (skip weekends)
            let day_of_week: u64 = ((timestamp / 86400000) + 4) % 7;
            if day_of_week < 5 {
                data.push(MarketData {
                    timestamp,
                    open,
                    high,
                    low,
                    close,
                    volume: 1000000 + (i as u64 * 1000),
                });
            }

            // Advance by one day
            timestamp += 86400000;
        }

        data
    }

    #[test]
    fn test_calculate_sma() {
        let prices: Vec<f64> = vec![10.0, 20.0, 30.0, 40.0, 50.0];

        // Test with period 3
        let sma3 = calculate_sma(&prices, 3);
        assert!(sma3.is_some());
        assert_eq!(sma3.unwrap(), 40.0); // (50 + 40 + 30) / 3

        // Test with period 5
        let sma5 = calculate_sma(&prices, 5);
        assert!(sma5.is_some());
        assert_eq!(sma5.unwrap(), 30.0); // (50 + 40 + 30 + 20 + 10) / 5

        // Test with insufficient data
        let sma10 = calculate_sma(&prices, 10);
        assert!(sma10.is_none());

        // Test with empty prices
        let empty: Vec<f64> = vec![];
        let sma_empty = calculate_sma(&empty, 3);
        assert!(sma_empty.is_none());

        // Test with zero period
        let sma_zero = calculate_sma(&prices, 0);
        assert!(sma_zero.is_none());
    }

    #[test]
    fn test_detect_crossover() {
        // Bullish crossover: fast was below, now above
        let result = detect_crossover(20.0, 25.0, 26.0, 25.0);
        assert_eq!(result, Some(1));

        // Bearish crossover: fast was above, now below
        let result = detect_crossover(30.0, 25.0, 24.0, 25.0);
        assert_eq!(result, Some(-1));

        // No crossover: both above
        let result = detect_crossover(30.0, 25.0, 35.0, 25.0);
        assert_eq!(result, None);

        // No crossover: both below
        let result = detect_crossover(20.0, 25.0, 22.0, 25.0);
        assert_eq!(result, None);

        // No crossover: exactly at same level
        let result = detect_crossover(25.0, 25.0, 26.0, 25.0);
        assert_eq!(result, Some(1));
    }

    #[test]
    fn test_market_hours() {
        // 9:30 AM EST on Jan 3, 2024
        let market_open: u64 = 1704295800000;
        assert!(is_market_hours(market_open));

        // 10:00 AM EST same day
        let mid_morning: u64 = 1704297600000;
        assert!(is_market_hours(mid_morning));

        // 4:00 PM EST (market close)
        let market_close: u64 = 1704319200000;
        assert!(!is_market_hours(market_close));

        // 9:00 AM EST (before open)
        let before_open: u64 = 1704294000000;
        assert!(!is_market_hours(before_open));

        // 5:00 PM EST (after close)
        let after_close: u64 = 1704322800000;
        assert!(!is_market_hours(after_close));

        // 9:29 AM EST (just before open)
        let just_before: u64 = 1704295740000;
        assert!(!is_market_hours(just_before));
    }

    #[test]
    fn test_signal_generation() {
        let data = generate_synthetic_aapl_data(100);
        let config = StrategyConfig::default();
        let mut strategy = LuxorTrendStrategy::new(config);
        let signals = strategy.generate_signals(&data);

        assert_eq!(signals.len(), data.len());

        // Check that we have at least some signals (not all Hold)
        let non_hold_signals: Vec<&Signal> = signals
            .iter()
            .filter(|s| s.action != Action::Hold)
            .collect();

        // With 100 days of data and a trending market, we should get some signals
        assert!(
            !non_hold_signals.is_empty(),
            "Expected some trading signals"
        );

        // Verify signal structure
        for signal in &signals {
            assert!(signal.confidence >= 0.0 && signal.confidence <= 1.0);
            assert!(signal.price > 0.0);
        }
    }

    #[test]
    fn test_backtest_calculation() {
        let data = generate_synthetic_aapl_data(100);
        let config = StrategyConfig::default();
        let mut strategy = LuxorTrendStrategy::new(config);
        let _signals = strategy.generate_signals(&data);
        let result = strategy.calculate_backtest(10000.0);

        // Verify result structure
        assert!(result.sharpe_ratio.is_finite());
        assert!(result.max_drawdown >= 0.0 && result.max_drawdown <= 1.0);
        assert!(result.total_return.is_finite());

        // Verify trades
        for trade in &result.trades {
            assert!(trade.entry_price > 0.0);
            assert!(trade.exit_price > 0.0);
            assert!(trade.entry_time > 0);
            assert!(trade.exit_time >= trade.entry_time);
            assert!(trade.quantity > 0.0);
        }
    }

    #[test]
    fn test_position_mae_mfe() {
        let mut position = Position::new(100.0, 1000, 1.0, 1);

        // Price goes up to 105
        position.update_mae_mfe(105.0);
        assert_eq!(position.max_favorable, 105.0);
        assert_eq!(position.max_adverse, 100.0);

        // Price drops to 98
        position.update_mae_mfe(98.0);
        assert_eq!(position.max_favorable, 105.0);
        assert_eq!(position.max_adverse, 98.0);

        // Check stop loss at 1.5% (entry was 100, stop at 98.5)
        assert!(position.check_stop_loss(98.0, 0.015));
        assert!(!position.check_stop_loss(99.0, 0.015));

        // Check profit target at 3% (entry was 100, target at 103)
        assert!(position.check_profit_target(103.0, 0.03));
        assert!(!position.check_profit_target(102.0, 0.03));
    }

    #[test]
    fn test_sharpe_ratio() {
        // Test with no returns
        let empty: Vec<f64> = vec![];
        assert_eq!(calculate_sharpe_ratio(&empty), 0.0);

        // Test with single return
        let single = vec![0.05];
        assert_eq!(calculate_sharpe_ratio(&single), 0.05);

        // Test with positive returns
        let positive = vec![0.01, 0.02, 0.015, 0.01, 0.025];
        let sharpe = calculate_sharpe_ratio(&positive);
        assert!(sharpe > 0.0);

        // Test with mixed returns
        let mixed = vec![0.05, -0.03, 0.04, -0.02, 0.03];
        let sharpe_mixed = calculate_sharpe_ratio(&mixed);
        assert!(sharpe_mixed.is_finite());
    }

    #[test]
    fn test_strategy_config_default() {
        let config = StrategyConfig::default();
        assert_eq!(config.fast_ma_period, 10);
        assert_eq!(config.slow_ma_period, 30);
        assert_eq!(config.mae_stop_pct, 0.015);
        assert_eq!(config.mfe_target_pct, 0.03);
        assert_eq!(config.quantity, 1.0);
    }

    #[test]
    fn test_wasm_bindings() {
        let data = generate_synthetic_aapl_data(50);
        let data_json = serde_json::to_string(&data).unwrap();

        // Test generate_signals_wasm
        let signals_json = generate_signals_wasm(&data_json);
        assert!(!signals_json.contains("error"));

        // Test run_backtest_wasm
        let backtest_json = run_backtest_wasm(&data_json);
        assert!(!backtest_json.contains("error"));
    }

    #[test]
    fn test_short_position_mae_mfe() {
        // Short position tracking
        let mut position = Position::new(100.0, 1000, 1.0, -1);

        // Price goes down to 95 (favorable for short)
        position.update_mae_mfe(95.0);
        assert_eq!(position.max_favorable, 95.0);
        assert_eq!(position.max_adverse, 100.0);

        // Price goes up to 105 (adverse for short)
        position.update_mae_mfe(105.0);
        assert_eq!(position.max_favorable, 95.0);
        assert_eq!(position.max_adverse, 105.0);

        // Check stop loss for short: 5% loss = 105, exceeds 1.5%
        assert!(position.check_stop_loss(105.0, 0.015));
    }

    #[test]
    fn test_crossover_with_realistic_prices() {
        // Simulate realistic price series where crossover occurs
        let prices: Vec<f64> = vec![
            100.0, 101.0, 102.0, 103.0, 104.0, // Uptrend
            105.0, 106.0, 107.0, 108.0, 109.0, 108.0, 107.0, 106.0, 105.0, 104.0, // Downtrend
            103.0, 102.0, 101.0, 100.0, 99.0,
        ];

        let mut fast_ma_values: Vec<f64> = Vec::new();
        let mut slow_ma_values: Vec<f64> = Vec::new();

        for i in 0..prices.len() {
            let slice = &prices[..=i];
            if let Some(fast) = calculate_sma(slice, 5) {
                fast_ma_values.push(fast);
            }
            if let Some(slow) = calculate_sma(slice, 10) {
                slow_ma_values.push(slow);
            }
        }

        // Verify we calculated MAs
        assert!(!fast_ma_values.is_empty());
        assert!(!slow_ma_values.is_empty());
    }
}
