//! Strategy Runtime Implementation for IronClaw
//!
//! Provides a secure WASM runtime for executing trading strategies using wasmtime
//! with WASI Preview 2 support. Includes backtesting, signal generation, and
//! resource tracking capabilities.
//!
//! All data exchange is done via JSON serialization over WASI stdin/stdout.

use crate::sandbox::SandboxConfig;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;
use std::time::Instant;
use tracing::{info, warn};
use wasmtime::{
    Config as EngineConfig, Engine, Linker, Module, Store, StoreLimits, StoreLimitsBuilder,
};
use wasmtime_wasi::p1::{self, WasiP1Ctx};
use wasmtime_wasi::p2::pipe::{MemoryInputPipe, MemoryOutputPipe};
use wasmtime_wasi::{DirPerms, FilePerms, WasiCtxBuilder};

/// Trading action types for strategy signals
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Action {
    /// Enter long position
    Buy,
    /// Exit position or enter short
    Sell,
    /// No action taken
    Hold,
}

/// Result of a backtest execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestResult {
    /// Sharpe ratio calculated from returns
    pub sharpe_ratio: f64,
    /// Maximum drawdown as percentage (0.0 to 1.0)
    pub max_drawdown: f64,
    /// Total return as percentage (0.0 to 1.0)
    pub total_return: f64,
    /// List of all executed trades
    pub trades: Vec<Trade>,
}

/// Market data point for a single timestamp
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketData {
    /// Unix timestamp in milliseconds
    pub timestamp: u64,
    /// Opening price
    pub open: f64,
    /// Highest price in period
    pub high: f64,
    /// Lowest price in period
    pub low: f64,
    /// Closing price
    pub close: f64,
    /// Trading volume
    pub volume: u64,
}

/// Resource usage metrics for WASM execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceUsage {
    /// Memory consumed in bytes
    pub memory_bytes: u64,
    /// CPU time consumed in milliseconds
    pub cpu_time_ms: u64,
}

/// Trading signal generated by a strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Unix timestamp in milliseconds when signal was generated
    pub timestamp: u64,
    /// Recommended trading action
    pub action: Action,
    /// Price at signal generation
    pub price: f64,
    /// Confidence score (0.0 to 1.0)
    pub confidence: f64,
}

/// Represents a completed trade
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    /// Entry price of the position
    pub entry_price: f64,
    /// Exit price of the position
    pub exit_price: f64,
    /// Quantity traded
    pub quantity: f64,
    /// Unix timestamp in milliseconds when position was opened
    pub entry_time: u64,
    /// Unix timestamp in milliseconds when position was closed
    pub exit_time: u64,
}

/// Trait defining the interface for strategy runtime implementations
///
/// Implementations must be thread-safe (`Send + Sync`) to allow concurrent
/// strategy execution across multiple threads.
pub trait StrategyRuntime: Send + Sync {
    /// Loads a WASM strategy module from the specified path
    ///
    /// # Arguments
    /// * `wasm_path` - Path to the compiled WASM module
    ///
    /// # Errors
    /// Returns an error if the WASM module cannot be loaded or validated
    fn load_strategy(&mut self, wasm_path: &Path) -> Result<(), anyhow::Error>;

    /// Runs a backtest using the loaded strategy against historical data
    ///
    /// # Arguments
    /// * `data` - Slice of market data points for the backtest period
    ///
    /// # Returns
    /// Backtest results including metrics and executed trades
    ///
    /// # Errors
    /// Returns an error if no strategy is loaded or execution fails
    fn run_backtest(&self, data: &[MarketData]) -> Result<BacktestResult, anyhow::Error>;

    /// Generates trading signals for the given market data
    ///
    /// # Arguments
    /// * `data` - Slice of market data points to analyze
    ///
    /// # Returns
    /// Vector of signals generated by the strategy
    ///
    /// # Errors
    /// Returns an error if no strategy is loaded or execution fails
    fn generate_signals(&self, data: &[MarketData]) -> Result<Vec<Signal>, anyhow::Error>;

    /// Retrieves current resource usage statistics
    ///
    /// # Returns
    /// Resource usage metrics including memory and CPU time
    ///
    /// # Errors
    /// Returns an error if resource tracking is unavailable
    fn get_resource_usage(&self) -> Result<ResourceUsage, anyhow::Error>;
}

/// WASI-compatible state for the wasmtime store
struct WasmState {
    /// WASI Preview 1 context for I/O operations
    ctx: WasiP1Ctx,
    /// Resource limits for the store
    limits: StoreLimits,
    /// Input data buffer for stdin
    stdin_buffer: Option<Vec<u8>>,
    /// Output data buffer for stdout
    stdout_buffer: Option<MemoryOutputPipe>,
}

impl WasmState {
    /// Creates a new WASI state with the given context and limits
    fn new(ctx: WasiP1Ctx, limits: StoreLimits) -> Self {
        Self {
            ctx,
            limits,
            stdin_buffer: None,
            stdout_buffer: None,
        }
    }

    /// Sets the stdin buffer with JSON-serialized data
    fn set_stdin_data<T: Serialize>(&mut self, data: &T) -> Result<()> {
        let json =
            serde_json::to_vec(data).context("Failed to serialize data to JSON for stdin")?;
        self.stdin_buffer = Some(json);
        Ok(())
    }

    /// Retrieves stdout data as a deserialized type
    fn get_stdout_data<T: for<'de> Deserialize<'de>>(&self) -> Result<T> {
        let buffer = self
            .stdout_buffer
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No stdout buffer available"))?;
        let data = buffer
            .clone()
            .try_into_inner()
            .ok_or_else(|| anyhow::anyhow!("Failed to read stdout buffer"))?;
        let result: T =
            serde_json::from_slice(&data).context("Failed to deserialize stdout data from JSON")?;
        Ok(result)
    }
}

/// wasmtime-based implementation of the StrategyRuntime trait
///
/// Uses WASI Preview 2 for secure sandboxed execution with resource limits,
/// JSON-based data exchange via stdin/stdout, and comprehensive metrics.
pub struct WasmtimeRunner {
    /// wasmtime execution engine
    engine: Engine,
    /// Optional loaded WASM module
    module: Option<Module>,
    /// Sandbox configuration for resource limits
    sandbox_config: SandboxConfig,
    /// Store limits for memory tracking
    store_limits: StoreLimits,
}

impl WasmtimeRunner {
    /// Creates a new WasmtimeRunner with the given sandbox configuration
    ///
    /// # Arguments
    /// * `sandbox_config` - Configuration for resource limits and security settings
    ///
    /// # Returns
    /// A new WasmtimeRunner instance ready to load strategies
    ///
    /// # Errors
    /// Returns an error if the wasmtime engine cannot be created
    pub fn new(sandbox_config: SandboxConfig) -> Result<Self> {
        info!(
            max_memory_mb = sandbox_config.max_memory_mb,
            max_runtime_seconds = sandbox_config.max_runtime_seconds,
            "Creating new WasmtimeRunner with sandbox configuration"
        );

        // Configure engine with WASI Preview 2 support
        let mut config = EngineConfig::new();
        config.wasm_component_model(true);

        let engine = Engine::new(&config)
            .map_err(|e| anyhow::anyhow!("Failed to create wasmtime engine: {}", e))?;

        // Convert MB to bytes for store limits
        let max_memory_bytes = sandbox_config.max_memory_mb * 1024 * 1024;

        let store_limits = StoreLimitsBuilder::new()
            .memory_size(max_memory_bytes as usize)
            .instances(1)
            .tables(1)
            .memories(1)
            .build();

        info!(
            max_memory_bytes = max_memory_bytes,
            "Configured wasmtime store limits"
        );

        Ok(Self {
            engine,
            module: None,
            sandbox_config,
            store_limits,
        })
    }

    /// Applies sandbox configuration to the WASI context
    ///
    /// Sets up stdin/stdout redirection, resource limits, and filesystem
    /// restrictions based on the sandbox configuration.
    fn apply_sandbox<T: Serialize>(&self, data: &T) -> Result<WasiP1Ctx> {
        info!("Applying sandbox configuration for WASM execution");

        // Serialize input data for stdin
        let stdin_data = serde_json::to_vec(data)
            .context("Failed to serialize input data for WASM execution")?;

        // Create stdin stream from serialized data
        let stdin = MemoryInputPipe::new(stdin_data);

        // Create stdout buffer for capturing output
        let stdout = MemoryOutputPipe::new(1024 * 1024); // 1MB buffer

        // Security-first minimal WASI surface: no network, controlled preopens only
        let mut builder = WasiCtxBuilder::new();

        // Configure stdin/stdout
        builder.stdin(stdin);
        builder.stdout(stdout.clone());

        // Add allowed paths for read-only access
        for path in &self.sandbox_config.allowed_paths {
            let path_str = path
                .to_str()
                .ok_or_else(|| anyhow::anyhow!("Invalid path encoding: {:?}", path))?;
            builder.preopened_dir(path, path_str, DirPerms::READ, FilePerms::READ)?;
            info!(path = %path_str, "Added preopened directory for read-only access");
        }

        // Disable network if not enabled
        if !self.sandbox_config.network_enabled {
            info!("Network access disabled in sandbox");
        }

        // Build the WASI Preview 1 context
        let wasi_ctx: WasiP1Ctx = builder.build_p1();
        Ok(wasi_ctx)
    }

    /// Executes the loaded WASM module with the given input data
    ///
    /// # Arguments
    /// * `data` - Market data to pass to the strategy via stdin
    ///
    /// # Returns
    /// The deserialized output from the WASM module
    ///
    /// # Errors
    /// Returns an error if no strategy is loaded or execution fails
    fn execute_wasm<T: Serialize, R: for<'de> Deserialize<'de>>(&self, data: &T) -> Result<R> {
        let module = self
            .module
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No strategy loaded. Call load_strategy() first"))?;

        info!("Executing WASM strategy");

        // Setup WASI context with sandbox
        let wasi_ctx = self.apply_sandbox(data)?;

        // Create store with limits
        let state = WasmState::new(wasi_ctx, self.store_limits.clone());
        let mut store = Store::new(&self.engine, state);

        // Set store limits for resource tracking
        store.limiter(|state| &mut state.limits);

        // Create linker and add WASI Preview 1
        let mut linker = Linker::<WasmState>::new(&self.engine);
        p1::add_to_linker_sync(&mut linker, |state: &mut WasmState| &mut state.ctx)
            .map_err(|e| anyhow::anyhow!("Failed to add WASI Preview 1 to linker: {}", e))?;

        // Instantiate the module
        let instance = linker
            .instantiate(&mut store, module)
            .map_err(|e| anyhow::anyhow!("Failed to instantiate WASM module: {}", e))?;

        // Get the main function and execute
        let main_func = instance
            .get_typed_func::<(), ()>(&mut store, "_start")
            .or_else(|_| instance.get_typed_func::<(), ()>(&mut store, "main"))
            .map_err(|e| {
                anyhow::anyhow!(
                    "Failed to find entry point function (_start or main): {}",
                    e
                )
            })?;

        // Track execution time
        let start_time = Instant::now();

        // Execute with timeout if configured
        let _result = main_func
            .call(&mut store, ())
            .map_err(|e| anyhow::anyhow!("WASM execution failed: {}", e))?;

        let elapsed = start_time.elapsed();
        info!(
            elapsed_ms = elapsed.as_millis() as u64,
            "WASM execution completed"
        );

        // Extract stdout data from store state
        let state_ref = store.data();
        let stdout_buffer = state_ref
            .stdout_buffer
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No stdout buffer available after execution"))?;

        let output_data = stdout_buffer
            .clone()
            .try_into_inner()
            .ok_or_else(|| anyhow::anyhow!("Failed to read stdout buffer"))?;

        if output_data.is_empty() {
            anyhow::bail!("WASM module produced no output");
        }

        // Deserialize the result
        let result: R = serde_json::from_slice(&output_data)
            .context("Failed to deserialize WASM output as JSON")?;

        Ok(result)
    }
}

impl StrategyRuntime for WasmtimeRunner {
    fn load_strategy(&mut self, wasm_path: &Path) -> Result<(), anyhow::Error> {
        info!(path = %wasm_path.display(), "Loading WASM strategy");

        // Validate path exists
        if !wasm_path.exists() {
            anyhow::bail!("WASM file not found: {}", wasm_path.display());
        }

        // Validate file extension
        if let Some(ext) = wasm_path.extension() {
            if ext != "wasm" && ext != "wasm32" {
                warn!(extension = %ext.to_string_lossy(), "File extension is not .wasm");
            }
        }

        // Load and compile the module
        let module = Module::from_file(&self.engine, wasm_path).map_err(|e| {
            anyhow::anyhow!(
                "Failed to load WASM module from: {}: {}",
                wasm_path.display(),
                e
            )
        })?;

        info!(
            name = module.name().unwrap_or("unnamed"),
            "WASM module loaded successfully"
        );

        self.module = Some(module);
        Ok(())
    }

    fn run_backtest(&self, data: &[MarketData]) -> Result<BacktestResult, anyhow::Error> {
        info!(data_points = data.len(), "Running backtest");

        if data.is_empty() {
            anyhow::bail!("Cannot run backtest with empty market data");
        }

        // Execute WASM with market data and expect BacktestResult
        let result: BacktestResult = self.execute_wasm(&data)?;

        info!(
            total_return = result.total_return,
            sharpe_ratio = result.sharpe_ratio,
            max_drawdown = result.max_drawdown,
            trade_count = result.trades.len(),
            "Backtest completed"
        );

        Ok(result)
    }

    fn generate_signals(&self, data: &[MarketData]) -> Result<Vec<Signal>, anyhow::Error> {
        info!(data_points = data.len(), "Generating trading signals");

        if data.is_empty() {
            anyhow::bail!("Cannot generate signals with empty market data");
        }

        // Execute WASM with market data and expect Vec<Signal>
        let signals: Vec<Signal> = self.execute_wasm(&data)?;

        info!(signal_count = signals.len(), "Signal generation completed");

        Ok(signals)
    }

    fn get_resource_usage(&self) -> Result<ResourceUsage, anyhow::Error> {
        // Since we don't have direct access to store after execution,
        // we return current limits as an approximation
        // In a production implementation, you'd track this during execution
        let memory_bytes = self.sandbox_config.max_memory_mb * 1024 * 1024;

        info!(
            memory_bytes = memory_bytes,
            "Retrieved resource usage (based on configured limits)"
        );

        Ok(ResourceUsage {
            memory_bytes,
            cpu_time_ms: 0, // Would need to track during actual execution
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_market_data_serialization() {
        let data = MarketData {
            timestamp: 1234567890,
            open: 100.0,
            high: 105.0,
            low: 98.0,
            close: 102.0,
            volume: 1000,
        };

        let json = serde_json::to_string(&data).unwrap();
        let deserialized: MarketData = serde_json::from_str(&json).unwrap();

        assert_eq!(data.timestamp, deserialized.timestamp);
        assert_eq!(data.close, deserialized.close);
    }

    #[test]
    fn test_signal_serialization() {
        let signal = Signal {
            timestamp: 1234567890,
            action: Action::Buy,
            price: 102.0,
            confidence: 0.85,
        };

        let json = serde_json::to_string(&signal).unwrap();
        let deserialized: Signal = serde_json::from_str(&json).unwrap();

        assert_eq!(signal.action, deserialized.action);
        assert_eq!(signal.confidence, deserialized.confidence);
    }

    #[test]
    fn test_backtest_result_serialization() {
        let result = BacktestResult {
            sharpe_ratio: 1.5,
            max_drawdown: 0.15,
            total_return: 0.25,
            trades: vec![Trade {
                entry_price: 100.0,
                exit_price: 110.0,
                quantity: 1.0,
                entry_time: 1234567890,
                exit_time: 1234567990,
            }],
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: BacktestResult = serde_json::from_str(&json).unwrap();

        assert_eq!(result.sharpe_ratio, deserialized.sharpe_ratio);
        assert_eq!(result.trades.len(), deserialized.trades.len());
    }

    #[test]
    fn test_action_variants() {
        assert_eq!(Action::Buy, Action::Buy);
        assert_ne!(Action::Buy, Action::Sell);
        assert_ne!(Action::Buy, Action::Hold);
    }

    #[test]
    fn test_wasmtime_runner_creation() {
        let config = SandboxConfig::new();
        let runner = WasmtimeRunner::new(config);
        assert!(runner.is_ok());
    }

    #[test]
    fn test_wasmtime_runner_without_strategy() {
        let config = SandboxConfig::new();
        let runner = WasmtimeRunner::new(config).unwrap();

        let data = vec![MarketData {
            timestamp: 1234567890,
            open: 100.0,
            high: 105.0,
            low: 98.0,
            close: 102.0,
            volume: 1000,
        }];

        let result = runner.run_backtest(&data);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("No strategy loaded"));
    }

    #[test]
    fn test_resource_usage_structure() {
        let usage = ResourceUsage {
            memory_bytes: 1024 * 1024,
            cpu_time_ms: 100,
        };

        let json = serde_json::to_string(&usage).unwrap();
        let deserialized: ResourceUsage = serde_json::from_str(&json).unwrap();

        assert_eq!(usage.memory_bytes, deserialized.memory_bytes);
        assert_eq!(usage.cpu_time_ms, deserialized.cpu_time_ms);
    }
}
